FROM debian:stretch

ENV \
	PYTHON_VERSION=3.6.3 \
	NGINX_VERSION=1.12.1 \
	GUNICORN_VERSION=19.7.1 \
	SUPERVISOR_VERSION=3.3.3 \
	NODE_VERSION=6.11.4 \
	NPM_VERSION=5.5.1 \
	YARN_VERSION=1.2.1 \
	LANG=en_US.UTF-8 \
	WWW_USER=www-data \
	WWW_GROUP=www-data \
	APP_ROOT=/app \
	INSTALL_ROOT=/usr/local \
	BUILD_ROOT=/tmp/build \
	TEMPLATE_DIR=/etc/deploy/templates \
	WEBPACK_CONFIG=/app/docker/webpack.config.js \
	PACKAGE_JSON=/app/docker/package.json

COPY install_base_deps.sh ${BUILD_ROOT}/install_base_deps.sh
RUN ${BUILD_ROOT}/install_base_deps.sh

COPY base/ ${BUILD_ROOT}/base/
RUN ${BUILD_ROOT}/base/run.sh && \
	rm -Rf ${BUILD_ROOT}/

COPY deploy/ /etc/deploy/
COPY entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
EXPOSE 80
