FROM debian:buster

ENV \
	PYTHON_VERSION=3.6.10 \
	NGINX_VERSION=1.17.9 \
	GUNICORN_VERSION=20.0.4 \
	SUPERVISOR_VERSION=4.1.0 \
	NODE_VERSION=12.16.1 \
	NPM_VERSION=6.14.2 \
	YARN_VERSION=1.22.4 \
	LANG=en_US.UTF-8 \
	WWW_USER=www-data \
	WWW_GROUP=www-data \
	APP_ROOT=/app \
	PROJ_ROOT=/app \
	INSTALL_ROOT=/usr/local \
	BUILD_ROOT=/tmp/build \
	READY_FILE=/run/ready \
	TEMPLATE_DIR=/etc/deploy/templates \
	WEBPACK_CONFIG=/app/docker/webpack.config.js \
	PACKAGE_JSON=/app/docker/package.json \
	PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    LANG=C.UTF-8 \
	PORT=8080 \
	HOST=0.0.0.0

COPY install_base_deps.sh ${BUILD_ROOT}/install_base_deps.sh
RUN ${BUILD_ROOT}/install_base_deps.sh

COPY base/ ${BUILD_ROOT}/base/
RUN ${BUILD_ROOT}/base/run.sh && \
	rm -Rf ${BUILD_ROOT}/

COPY deploy/ /etc/deploy/
COPY entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
EXPOSE $PORT
VOLUME [ "/var/log" ]
