FROM tbeadle/gunicorn-docker:3.5

COPY build_app.sh /usr/local/bin/
WORKDIR ${APP_ROOT}
ONBUILD COPY docker/ ${APP_ROOT}/docker/
ONBUILD RUN build_app.sh
# Copy the whole app at the end so that rebuilding the image when changes are
# only made in the app code (as opposed to its dependencies) doesn't cause all
# the dependencies to be reinstalled.
ONBUILD COPY . ${APP_ROOT}/
